storage: /tmp/verdaccio/storage
plugins: ./plugins

web:
  enable: true
  title: Verdaccio

auth:
  htpasswd:
    file: /tmp/verdaccio/htpasswd

packages:
  '@*/*':
    access: $all
    publish: $all
    proxy: None
  '**':
    access: $all
    publish: $all
    proxy: None

server:
  keepAliveTimeout: 60

middlewares:
  audit:
    enabled: true

max_body_size: 200mb 
logs:
  - {type: stdout, format: pretty, level: error}
